apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-enterprise-app
  labels:
    app: {{ .Release.Name }}-enterprise-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-enterprise-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-enterprise-app
    spec:
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
