apiVersion: v1
kind: Pod
metadata:
  name: devops-first-pod
  labels:
    app: first-pod
    session: "09"
    student: hitarth
spec:
  containers:
  - name: web
    image: nginx:alpine
    ports:
    - containerPort: 80
