apiVersion: v1
kind: Secret
metadata:
  name: app-db-credentials
type: Opaque
# Values base64 encoded:
# root_password: echo -n 'SuperSecretPass123!' | base64 -> U3VwZXJTZWNyZXRQYXNzMTIzIQ==
# api_key: echo -n 'ak_live_99214a1a5b8' | base64 -> YWtfbGl2ZV85OTIxNGExYTViOA==
data:
  DB_PASSWORD: U3VwZXJTZWNyZXRQYXNzMTIzIQ==
  API_KEY: YWtfbGl2ZV85OTIxNGExYTViOA==
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-demo
spec:
  containers:
  - name: test-app
    image: busybox:1.36
    command: ["sh", "-c", "echo API_KEY injected: $API_KEY; echo Secret file:; cat /etc/secrets/DB_PASSWORD; sleep 3600"]
    env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: app-db-credentials
          key: API_KEY
    volumeMounts:
    - name: secret-vol
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: app-db-credentials
