apiVersion: v1
kind: Service
metadata:
  name: external-database-svc
spec:
  type: ExternalName
  # Maps internal cluster DNS to an external CNAME record without proxying traffic
  externalName: my-db.us-east-1.rds.amazonaws.com
